trigger:
- none 

variables:
  IISWebsiteName: 'Default Web Site'

resources:  
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'AzureTestProject'
      source: 'Build Pipeline'
      branch: 'master'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy Website'
    pool:
      name: 'Onprem-UAT-Agent'
    
    jobs:
      - deployment: DeployWebsite
        displayName: 'Deploy Website'
        environment: 'FBL_UAT_ENVIRONMENT.FBLUATAZDEVPSVR'
        strategy:
         runOnce:
           deploy:
            steps:
              - checkout: none

              - download: 'buildPipeline'
                name: 'DownloadBuildArtifacts'
                displayName: 'Download Build Artifacts'
                artifact: 'drop'
                 
              - task: IISWebAppManagementOnMachineGroup@0
                name: 'StopIIS'
                displayName: 'Stop IIS website'
                inputs:
                  IISDeploymentType: 'IISWebsite'
                  ActionIISWebsite: 'StopWebsite'
                  StartStopWebsiteName: '${{variables.IISWebsiteName}}'

              - task: ExtractFiles@1
                name: 'ExtractWebDeployPackage'
                displayName: 'Extract Web Deploy Package'
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)\buildPipeline\drop\SampleWebApp.zip'  # or specify the exact zip file
                  destinationFolder: '$(Pipeline.Workspace)\unzipped'
                  cleanDestinationFolder: true
                
              
              - task: IISWebAppDeploymentOnMachineGroup@0
                name: 'DeployIIS'
                displayName: 'Deploy IIS website'
                inputs:
                  WebSiteName: '${{ variables.IISWebsiteName }}'
                  Package: '$(Pipeline.Workspace)\unzipped'
                  TakeAppOfflineFlag: true
              
              - task: IISWebAppManagementOnMachineGroup@0
                name: 'StartIIS'
                displayName: 'Start IIS website' 
                inputs:
                  IISDeploymentType: 'IISWebsite'
                  ActionIISWebsite: 'StartWebsite'
                  StartStopWebsiteName: '${{variables.IISWebsiteName}}'




